# -*- coding: utf-8 -*-
"""Social listening sobre el consumo de crédito en México.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t-fdiVH2ISH2j3Fpp-_GU12hk5AUEvmr

##Social listening sobre el consumo de crédito en México##

El siguiente trabajo pretende analisar el consumo de crédito y cómo es su promoción en redes sociodigitales.
"""

import